language: node_js
node_js:
  - "14.18.0"
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache
install:
  - make install
jobs:
  include:
    - stage: test
      if: type = pull_request
      script: yarn test.cypress
